main: io.github.aleksandarharalanov.ferns.Ferns
version: 1.1.0
name: Ferns
author: Beezle
website: github.com/AleksandarHaralanov/Ferns
description: Converts tall grass placement to a fern.

commands:
  ferns:
    description: See Ferns information.
    default: op